# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - containedctx
    - errcheck
    - errname
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - reassign
    - staticcheck
    - typecheck
    - unused
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0