# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
  - dupl
  - funlen
  - gochecknoglobals
  - lll
  - revive
  - varnamelen

linters-settings:
  paralleltest:
    ignore-missing: true
  interfacebloat:
    max: 20

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0