packages:
  github.com/greencoda/tasq:
    config:
      pkgname: 'mocks'
      filename: "{{.InterfaceName}}.go"
      structname: "{{.InterfaceName}}"
      dir: "./mocks"
    interfaces:
      IRepository:
