// Code generated by mockery v2.25.1. DO NOT EDIT.

package mocks

import (
	context "context"

	tasq "github.com/greencoda/tasq"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// CleanTasks provides a mock function with given fields: ctx, minimumAge
func (_m *IRepository) CleanTasks(ctx context.Context, minimumAge time.Duration) (int64, error) {
	ret := _m.Called(ctx, minimumAge)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (int64, error)); ok {
		return rf(ctx, minimumAge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = rf(ctx, minimumAge)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, minimumAge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountTasks provides a mock function with given fields: ctx, taskStatuses, taskTypes, queues
func (_m *IRepository) CountTasks(ctx context.Context, taskStatuses []tasq.TaskStatus, taskTypes []string, queues []string) (int64, error) {
	ret := _m.Called(ctx, taskStatuses, taskTypes, queues)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string) (int64, error)); ok {
		return rf(ctx, taskStatuses, taskTypes, queues)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string) int64); ok {
		r0 = rf(ctx, taskStatuses, taskTypes, queues)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []tasq.TaskStatus, []string, []string) error); ok {
		r1 = rf(ctx, taskStatuses, taskTypes, queues)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: ctx, task, safeDelete
func (_m *IRepository) DeleteTask(ctx context.Context, task *tasq.Task, safeDelete bool) error {
	ret := _m.Called(ctx, task, safeDelete)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task, bool) error); ok {
		r0 = rf(ctx, task, safeDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Migrate provides a mock function with given fields: ctx
func (_m *IRepository) Migrate(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PingTasks provides a mock function with given fields: ctx, taskIDs, visibilityTimeout
func (_m *IRepository) PingTasks(ctx context.Context, taskIDs []uuid.UUID, visibilityTimeout time.Duration) ([]*tasq.Task, error) {
	ret := _m.Called(ctx, taskIDs, visibilityTimeout)

	var r0 []*tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Duration) ([]*tasq.Task, error)); ok {
		return rf(ctx, taskIDs, visibilityTimeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID, time.Duration) []*tasq.Task); ok {
		r0 = rf(ctx, taskIDs, visibilityTimeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID, time.Duration) error); ok {
		r1 = rf(ctx, taskIDs, visibilityTimeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PollTasks provides a mock function with given fields: ctx, types, queues, visibilityTimeout, ordering, limit
func (_m *IRepository) PollTasks(ctx context.Context, types []string, queues []string, visibilityTimeout time.Duration, ordering tasq.Ordering, limit int) ([]*tasq.Task, error) {
	ret := _m.Called(ctx, types, queues, visibilityTimeout, ordering, limit)

	var r0 []*tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, time.Duration, tasq.Ordering, int) ([]*tasq.Task, error)); ok {
		return rf(ctx, types, queues, visibilityTimeout, ordering, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, time.Duration, tasq.Ordering, int) []*tasq.Task); ok {
		r0 = rf(ctx, types, queues, visibilityTimeout, ordering, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string, time.Duration, tasq.Ordering, int) error); ok {
		r1 = rf(ctx, types, queues, visibilityTimeout, ordering, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PurgeTasks provides a mock function with given fields: ctx, taskStatuses, taskTypes, queues, safeDelete
func (_m *IRepository) PurgeTasks(ctx context.Context, taskStatuses []tasq.TaskStatus, taskTypes []string, queues []string, safeDelete bool) (int64, error) {
	ret := _m.Called(ctx, taskStatuses, taskTypes, queues, safeDelete)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string, bool) (int64, error)); ok {
		return rf(ctx, taskStatuses, taskTypes, queues, safeDelete)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string, bool) int64); ok {
		r0 = rf(ctx, taskStatuses, taskTypes, queues, safeDelete)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []tasq.TaskStatus, []string, []string, bool) error); ok {
		r1 = rf(ctx, taskStatuses, taskTypes, queues, safeDelete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterError provides a mock function with given fields: ctx, task, errTask
func (_m *IRepository) RegisterError(ctx context.Context, task *tasq.Task, errTask error) (*tasq.Task, error) {
	ret := _m.Called(ctx, task, errTask)

	var r0 *tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task, error) (*tasq.Task, error)); ok {
		return rf(ctx, task, errTask)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task, error) *tasq.Task); ok {
		r0 = rf(ctx, task, errTask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tasq.Task, error) error); ok {
		r1 = rf(ctx, task, errTask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterFinish provides a mock function with given fields: ctx, task, finishStatus
func (_m *IRepository) RegisterFinish(ctx context.Context, task *tasq.Task, finishStatus tasq.TaskStatus) (*tasq.Task, error) {
	ret := _m.Called(ctx, task, finishStatus)

	var r0 *tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task, tasq.TaskStatus) (*tasq.Task, error)); ok {
		return rf(ctx, task, finishStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task, tasq.TaskStatus) *tasq.Task); ok {
		r0 = rf(ctx, task, finishStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tasq.Task, tasq.TaskStatus) error); ok {
		r1 = rf(ctx, task, finishStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterStart provides a mock function with given fields: ctx, task
func (_m *IRepository) RegisterStart(ctx context.Context, task *tasq.Task) (*tasq.Task, error) {
	ret := _m.Called(ctx, task)

	var r0 *tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) (*tasq.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) *tasq.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tasq.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequeueTask provides a mock function with given fields: ctx, task
func (_m *IRepository) RequeueTask(ctx context.Context, task *tasq.Task) (*tasq.Task, error) {
	ret := _m.Called(ctx, task)

	var r0 *tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) (*tasq.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) *tasq.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tasq.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScanTasks provides a mock function with given fields: ctx, taskStatuses, taskTypes, queues, ordering, limit
func (_m *IRepository) ScanTasks(ctx context.Context, taskStatuses []tasq.TaskStatus, taskTypes []string, queues []string, ordering tasq.Ordering, limit int) ([]*tasq.Task, error) {
	ret := _m.Called(ctx, taskStatuses, taskTypes, queues, ordering, limit)

	var r0 []*tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string, tasq.Ordering, int) ([]*tasq.Task, error)); ok {
		return rf(ctx, taskStatuses, taskTypes, queues, ordering, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []tasq.TaskStatus, []string, []string, tasq.Ordering, int) []*tasq.Task); ok {
		r0 = rf(ctx, taskStatuses, taskTypes, queues, ordering, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []tasq.TaskStatus, []string, []string, tasq.Ordering, int) error); ok {
		r1 = rf(ctx, taskStatuses, taskTypes, queues, ordering, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitTask provides a mock function with given fields: ctx, task
func (_m *IRepository) SubmitTask(ctx context.Context, task *tasq.Task) (*tasq.Task, error) {
	ret := _m.Called(ctx, task)

	var r0 *tasq.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) (*tasq.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tasq.Task) *tasq.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tasq.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tasq.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRepository(t mockConstructorTestingTNewIRepository) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
